# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the U-Boot SMEM interface drivers

obj-$(CONFIG_SANDBOX_SMEM) += sandbox_smem.o
obj-$(CONFIG_$(PHASE_)SMEM) += smem-uclass.o
obj-$(CONFIG_$(PHASE_)MSM_SMEM) += msm_smem.o
